<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CraftsVilla" duration-ms="69349" started-at="2019-05-05T16:17:57Z" finished-at="2019-05-05T16:19:06Z">
    <groups>
    </groups>
    <test name="Regression" duration-ms="69349" started-at="2019-05-05T16:17:57Z" finished-at="2019-05-05T16:19:06Z">
      <class name="com.craftsvilla.testscripts.CottonSareesScripts">
        <test-method status="PASS" signature="openApplication(java.lang.String)[pri:0, instance:com.craftsvilla.testscripts.CottonSareesScripts@69a3d1d]" name="openApplication" is-config="true" duration-ms="27100" started-at="2019-05-05T16:17:57Z" finished-at="2019-05-05T16:18:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApplication -->
        <test-method status="FAIL" signature="TC_01_ChooseCottonSaree()[pri:0, instance:com.craftsvilla.testscripts.CottonSareesScripts@69a3d1d]" name="TC_01_ChooseCottonSaree" duration-ms="40365" started-at="2019-05-05T16:18:24Z" finished-at="2019-05-05T16:19:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.craftsvilla.testscripts.CottonSareesScripts.TC_01_ChooseCottonSaree(CottonSareesScripts.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_ChooseCottonSaree -->
      </class> <!-- com.craftsvilla.testscripts.CottonSareesScripts -->
    </test> <!-- Regression -->
  </suite> <!-- CraftsVilla -->
</testng-results>
